'__impl__'/1
Function move_to/3 only terminates with explicit exception
